project:
  title: "Case-studies"
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - Case-study-1.qmd

website: 
  title: "Case studies for Open Access sessions"
  repo-url: https://nicki-clarkson.github.io/Case-studies
  repo-branch: main
  repo-actions:
  - edit
  - issue
  sidebar: 
    style: docked
    search: true
    contents:
      - href: index.qmd
        text: Introduction
      - href: Case-study-1.qmd
        text: "Case study 1"
  page-footer: "Created by the University of Southampton Library with a CC0 licence"
        
format: 
  html: 
    link-external-newwindow: true
    link-external-icon: true
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-depth: 3
    toc-expand: true
    standalone: true
editor: visual
